#!/bin/bash
##===----------------------------------------------------------------------===##
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##===----------------------------------------------------------------------===##
# Downloads the third-party assets (fonts, lottie-player) that book/theme/
# head.hbs and index.hbs fall back to at runtime if the CDN is unreachable,
# into book/theme/vendor-cache/ — a gitignored, generated directory, not
# checked into version control.
#
# Not required to build or serve the book: mdbook itself never needs network
# access. This just pre-warms the local fallback so a browser viewing the
# book with no network access still gets working fonts/lottie-player instead
# of a failed CDN request with no local copy to fall back to.
#
# Safe to re-run: skips files that already exist unless --force is passed.
#
# Usage: bash scripts/fetch_offline_assets.sh [--force]

set -euo pipefail

BOOK_DIR="$(cd "$(dirname "$0")/../book" && pwd)"
CACHE_DIR="$BOOK_DIR/theme/vendor-cache"
FORCE=false
[[ "${1:-}" == "--force" ]] && FORCE=true

mkdir -p "$CACHE_DIR/fonts"

fetch() {
    local url="$1" dest="$2"
    if [[ -f "$dest" ]] && ! $FORCE; then
        echo "[skip] $dest already exists"
        return
    fi
    echo "[fetch] $url -> $dest"
    curl -fsSL "$url" -o "$dest"
}

# lottiefiles/lottie-player — powers the puzzle solution reveal animation
# (see book/theme/solution.js). Pinned version, MIT license.
LOTTIE_VERSION="2.0.12"
fetch "https://unpkg.com/@lottiefiles/lottie-player@$LOTTIE_VERSION/dist/lottie-player.js" \
    "$CACHE_DIR/lottie-player.js"

# Google Fonts — latin-only subset (this book is English + Korean; neither
# typeface covers Hangul, so Korean already falls back to system fonts
# regardless of online/offline mode). OFL license.
fetch "https://fonts.gstatic.com/s/robotomono/v31/L0x7DF4xlVMF-BfR8bXMIjhOm32WWg.woff2" \
    "$CACHE_DIR/fonts/roboto-mono-italic.woff2"
fetch "https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq38.woff2" \
    "$CACHE_DIR/fonts/roboto-mono-regular.woff2"
fetch "https://fonts.gstatic.com/s/inter/v20/UcCm3FwrK3iLTcvnUwQT9g.woff2" \
    "$CACHE_DIR/fonts/inter-italic.woff2"
fetch "https://fonts.gstatic.com/s/inter/v20/UcCo3FwrK3iLTcviYwY.woff2" \
    "$CACHE_DIR/fonts/inter-regular.woff2"

# Regenerate the @font-face wrapper CSS every run — cheap, and keeps it in
# sync if the unicode-range/weight declarations above ever change.
cat > "$CACHE_DIR/fonts/roboto-mono.css" <<'EOF'
/* Vendored subset (latin) of Roboto Mono, downloaded from Google Fonts (v31).
   Generated by scripts/fetch_offline_assets.sh; do not edit by hand. */
@font-face {
  font-family: 'Roboto Mono';
  font-style: italic;
  font-weight: 100 700;
  font-display: swap;
  src: url('roboto-mono-italic.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Roboto Mono';
  font-style: normal;
  font-weight: 100 700;
  font-display: swap;
  src: url('roboto-mono-regular.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
EOF

cat > "$CACHE_DIR/fonts/inter.css" <<'EOF'
/* Vendored subset (latin) of Inter, downloaded from Google Fonts (v20).
   Generated by scripts/fetch_offline_assets.sh; do not edit by hand. */
@font-face {
  font-family: 'Inter';
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url('inter-italic.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url('inter-regular.woff2') format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
EOF

cat > "$CACHE_DIR/NOTICE.md" <<EOF
Generated by \`scripts/fetch_offline_assets.sh\` — gitignored, not checked into
version control. Re-run that script (optionally with \`--force\`) to refresh.

| File | Source | Version | License |
|---|---|---|---|
| \`lottie-player.js\` | https://unpkg.com/@lottiefiles/lottie-player | $LOTTIE_VERSION | MIT |
| \`fonts/roboto-mono.css\` + \`fonts/roboto-mono-*.woff2\` | Google Fonts, Roboto Mono | v31, latin subset only | OFL |
| \`fonts/inter.css\` + \`fonts/inter-*.woff2\` | Google Fonts, Inter | v20, latin subset only | OFL |
EOF

echo "Offline assets ready in $CACHE_DIR"
