##===----------------------------------------------------------------------===##
# Copyright (c) 2026, Modular Inc. All rights reserved.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions:
# https://llvm.org/LICENSE.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##===----------------------------------------------------------------------===##
name: Publish Puzzles

on:
  push:
    branches:
      - stable
    paths:
      - "pixi.lock"
  pull_request:
    branches:
      - stable
    paths:
      - "pixi.lock"

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.modular
            ~/.cache/modular
          key: ${{ runner.os }}-modular-${{ hashFiles('**/pixi.toml') }}

      - uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293
        with:
          pixi-version: v0.71.0
          cache: false
          post-cleanup: false

      - name: Build
        shell: bash
        run: |
          cd book
          pixi run build-book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4b09552702d0b65573696410d4707c765da2630b
        if: github.event_name == 'push' && github.ref == 'refs/heads/stable'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/html
          cname: puzzles.modular.com
          allow_empty_commit: true
